project:
  type: website
website:
  title: "STAT 515 Final Project"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data"
        href: data.qmd
      - text: "Analysis"
        href: analysis.qmd
      - text: "Discussion"
        href: discussion.qmd
      - text: "References"
        href: references.qmd
      - text: "About"
        href: about.qmd
format:
  html:
    theme: flatly
    css: styles.css
    code-fold: true
    toc: true
    toc-depth: 3


